<?php


namespace App\Models;

/**
 * Class UserPermissions
 *
 * The various permissions that users can have
 *
 * @package App\Models
 */
abstract class UserPermissions
{
    // Admin User Permissions
    const CAN_CRUD_USERS = "CAN_CRUD_USERS";

    // Loan Permissions
    const CAN_CREATE_LOAN_APPLICATIONS = "CAN_CREATE_LOAN_APPLICATIONS";
    const CAN_CREATE_LOANS = "CAN_CREATE_LOANS";
    const CAN_UPDATE_LOAN_STATUS = "CAN_UPDATE_LOAN_STATUS";
    const CAN_DISBURSE_LOAN = "CAN_DISBURSE_LOAN";
    const CAN_INITIATE_LOAN_REPAYMENT = "CAN_INITIATE_LOAN_REPAYMENT";
//    const CAN_APPROVE_LOAN_REPAYMENT = "CAN_APPROVE_LOAN_REPAYMENT";

    // Contribution plan permissions
    const CAN_CREATE_CONTRIBUTION = "CAN_CREATE_CONTRIBUTION";
    const CAN_UPDATE_CONTRIBUTION = "CAN_UPDATE_CONTRIBUTION";
    const CAN_DELETE_CONTRIBUTION = "CAN_DELETE_CONTRIBUTION";
    const CAN_INITIATE_CONTRIBUTION_PLAN_TRANSACTION = "CAN_INITIATE_CONTRIBUTION_PLAN_TRANSACTION";
//    const CAN_APPROVE_CONTRIBUTION_PLAN_TRANSACTION = "CAN_APPROVE_CONTRIBUTION_PLAN_TRANSACTION";

    const CAN_PROCESS_TRANSACTION = "CAN_PROCESS_TRANSACTION";
}
